default_platform(:android)

platform :android do
  desc "Build unsigned release APK"
  lane :build_unsigned_apk do
    gradle(
      task: "assembleRelease",
      project_dir: "android/"
    )
  end
end
