name: Build unsigned APK

on:
  push:
    branches:
      - development

jobs:
  build:
    name: Build unsigned APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run Fastlane lane (build unsigned APK)
        uses: maierj/fastlane-action@v3.1.0
        with:
          lane: android build_unsigned_apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-apk
          path: build/app/outputs/flutter-apk/app-release.apk
